version: "3.6"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    entrypoint: /usr/src/app/api-entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine 
    restart: always
    ports:
      - "5437:5432"
    environment:
     - POSTGRES_DB=lfg_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
  
  rabbit:
    image: rabbitmq:3
    ports:
      - "5673:5672"
    restart: always 

  celery:
    build:
        context: ./api
        dockerfile: Dockerfile
    command: celery -A setup.celery worker -l INFO
    restart: always
    depends_on:
      - rabbit

  interface:
    build:
        context: ./interface
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node app.js
    restart: always
    depends_on:
      - api