# Generated by Django 4.2 on 2023-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document', models.JSONField()),
                ('is_api_approved', models.BooleanField(default=False)),
                ('is_admin_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'All Submitted Loan',
            },
        ),
        migrations.CreateModel(
            name='LoanField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('month', 'Month'), ('time', 'Time'), ('email', 'E-mail')], default='text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('order_number', models.IntegerField(unique=True, verbose_name='Order number                                       (Frontend input order) ')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedLoan',
            fields=[
            ],
            options={
                'verbose_name': 'API Approved Loan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lfg_api.loan',),
        ),
    ]
